### ISSUE TITLE
ci(Argos): Not working as expected

### ISSUE THREAD

**Issue by nokome** [stencila/thema#53] opened 2020-02-17 20:18 UTC
I don't think that Argos is working as expected. 

Exhibit A is Argos build 61604 (note that there is a bug with some of the Argos links and displayed build numbers https://github.com/argos-ci/argos/issues/412; this may or may not be related to this issue):

https://www.argos-ci.com/stencila/thema/builds/61604

Those screenshots came from this Travis build: https://travis-ci.org/stencila/thema/builds/651041183#L674

The screenshots are displaying an error probably because I wrongly removed the `SAUCE_API_HOST` env var:

https://github.com/stencila/thema/compare/b3a019a89b3cea0ca6287ee997edaee5031fd1f8...01216350355b#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L25

But the point of this issue is not that error, but that Argos did not see build 61604 as a visual regression from the previous build (in which the screenshots were OK):

https://www.argos-ci.com/stencila/thema/builds/61603

**Comment by nokome** [comment] 2020-02-17 21:01
Added `SAUCE_API_HOST` env var to the Travis build settings:

https://travis-ci.org/stencila/thema/builds/651051212#L178

And Argos builds now show correct screenshots, but still no error regarding regressions:

https://www.argos-ci.com/stencila/thema/builds/61651

**Comment by alex-ketch** [comment] 2020-02-18 15:12
Think the reason for the lack of regression reports might be due to the PRs targeting the `next` branch.
Since we originally set up the integration with `master` being the default branch, I believe Argos is using it as a reference. The second part of the lack of references though I think is because the file names have changes, no references exist on for the screenshots being taken.
There are a couple of issues (https://github.com/argos-ci/argos/issues/154, https://github.com/argos-ci/argos/issues/154) that hint at this.
I think once we switch back to targeting the `master` branch, and have one full build, differences will start being reported again.

**Comment by alex-ketch** [comment] 2021-03-11 02:49
This was closed by migrating to Percy in https://github.com/stencila/thema/pull/286

**Closed by alex-ketch** 2021-03-11 02:49 UTC
Labels: bug
